### ISSUE TITLE
Code shown in .Summary

### ISSUE THREAD

**Issue by Lithimlin** [martignoni/hugo-cloak-email#4] opened 2019-05-15 06:50 UTC
During Pagination, the code of the `cloakemail` shortcode is plainly inserted when using the `.Summary` variable.

Code/Content needed to replicate this:
1) Have some type of content with a cloaked email within the summary
2) Paginate that content and use the `.Summary` variable:
```
{{ $paginator := .Paginate (where .Site.RegularPages "Section" "mySection")}}
{{ range $paginator.Pages }}
    {{.Summary}}
{{ end }}
```
The result is the following shown plainly on the website:
```
{ content:attr(data-domain) "\0040" attr(data-user); unicode-bidi:bidi-override; direction:rtl; } var scriptTag = document.getElementById("a5edcb9119308c736e104980d902d913"); var link = document.createElement("a"); var address = "nielgnetsh".split('').reverse().join('') + "@" + "ed.tsi-sf".split('').reverse().join(''); link.href = "mailto" + ":" + address; link.innerText = address; scriptTag.parentElement.insertBefore(link, scriptTag.previousElementSibling); scriptTag.parentElement.removeChild(scriptTag.previousElementSibling)
```
How can I fix and/or avoid this issue?

**Comment by martignoni** [comment] 2019-05-18 10:04
I can't reproduce your problem. Do you have a online site (with a public repo) showing this?

**Comment by Lithimlin** [comment] 2019-05-18 18:20
Unfortunately, the site is not live *yet*, but I can show you a screenshot and the markdown text.
![website-mail-cloaking](https://user-images.githubusercontent.com/25646100/57973523-5b058380-79aa-11e9-87cb-99a92f955092.png)
```
Leute die Probleme mit einem gelöschten Account im Informatik Moodle haben, können sich bei Hans unter {{< cloakemail "hstenglein@fs-ist.de" >}} melden, damit er das gesammelt an Guido Rößling weiterleiten kann.
en kann.
```

**Comment by martignoni** [comment] 2019-05-18 18:24
I'm afraid this doesn't help. Without the source code I'm not able to diagnose the problem.

**Comment by Lithimlin** [comment] 2019-05-18 18:27
Hmm.. I gave you pretty much all the relevant source code.
Maybe it's a problem with hugo's `plainify`command. I'm not sure if the `.Summary` variable makes use of that.

**Comment by martignoni** [comment] 2019-05-18 18:35
>  I gave you pretty much all the relevant source code.

I mean: not the content source code, but the layout, shortcodes, etc. As [stated here](https://discourse.gohugo.io/t/requesting-help/9132) one needs _the context_ of seeing your templates and partials to be able to help you

> Maybe it's a problem with hugo's `plainify` command. I'm not sure if the .Summary variable makes use of that.

As already noted: I tested my shortcode inside a summary within a pagination, and could not reproduce, hence my question about the source.

**Comment by Lithimlin** [comment] 2019-05-18 18:45
> As already noted: I tested my shortcode inside a summary within a pagination, and could not reproduce, hence my question about the source.

Weird. It does that for me no matter where I add a summary of a text with a cloaked mail inside it. Maybe I configured something incorrectly?

**Comment by martignoni** [comment] 2020-03-08 16:04
Closing, since cannot test on the repo.

**Closed as completed by martignoni** 2020-03-08 16:04 UTC
Labels: invalid
